module(load="imuxsock")
module(load="imjournal")

*.info;mail.none;authpriv.none;cron.none    /var/log/messages
authpriv.*                                  /var/log/secure

# Пересылка на центральный сервер сбора событий
action(type="omfwd" target="siem.example.test" port="6514" protocol="tcp"
       StreamDriver="gtls" StreamDriverMode="1" StreamDriverAuthMode="x509/name")
